// A-006 — Dynamic site generation (pure, deterministic).
// Rebuilds a deployable, data-driven site from the crawled dataset: a
// dependency-free single-page app (index.html + app.js) that loads
// `data/pages.json` and renders every crawled page via hash routing, plus a
// stylesheet reconstructed from captured design tokens. Zero build step —
// deploy the folder to any static host (Vercel/Netlify/GH Pages) for a live
// clone that serves the full crawled dataset.

import type { CaptureBundle, GeneratedSite, GeneratedSiteFile, SiteDataset } from './clone-types.js';

const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Cloned Site</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="shell">
  <header class="topbar">
    <a class="brand" href="#/">Cloned Site</a>
    <span class="origin" id="origin"></span>
  </header>
  <div class="layout">
    <nav class="sidebar" id="nav"></nav>
    <main class="content" id="content"></main>
  </div>
  <footer class="footer">Generated by vdd:clone &mdash; content crawled from the source site.</footer>
</div>
<script src="app.js"></script>
</body>
</html>
`;

const APP_JS = `(function () {
  'use strict';
  var PAGES = [];
  var BY_PATH = {};
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  function route() {
    var h = location.hash || '#/';
    var p = '';
    try { p = decodeURIComponent(h.slice(1)); } catch (e) { p = h.slice(1); }
    return p || '/';
  }
  function groupNav() {
    var groups = {};
    PAGES.forEach(function (p) {
      var seg = (p.path.split('/').filter(Boolean)[0]) || 'home';
      if (!groups[seg]) groups[seg] = [];
      groups[seg].push(p);
    });
    return groups;
  }
  function renderNav() {
    var cur = route();
    var g = groupNav();
    var html = '<a class="nav-item' + (cur === '/' ? ' active' : '') + '" href="#/">All pages (' + PAGES.length + ')</a>';
    Object.keys(g).sort().forEach(function (seg) {
      html += '<div class="nav-group">' + esc(seg) + '</div>';
      g[seg].sort(function (a, b) { return (a.path < b.path ? -1 : 1); }).forEach(function (p) {
        html += '<a class="nav-item' + (cur === p.path ? ' active' : '') + '" href="#' + p.path + '">' + esc(p.title || p.path) + '</a>';
      });
    });
    document.getElementById('nav').innerHTML = html;
  }
  function renderHome() {
    var rows = PAGES.slice().sort(function (a, b) { return (a.path < b.path ? -1 : 1); }).map(function (p) {
      return '<a class="card" href="#' + p.path + '">' +
        '<div class="card-title">' + esc(p.title || p.path) + '</div>' +
        '<div class="card-path">' + esc(p.path) + '</div>' +
        (p.description ? '<div class="card-desc">' + esc(p.description) + '</div>' : '') +
      '</a>';
    }).join('');
    document.getElementById('content').innerHTML = '<h1>Pages</h1><div class="cards">' + (rows || '<p>No pages.</p>') + '</div>';
  }
  function renderPage(p) {
    var heads = (p.headings || []).map(function (h) { return '<h3>' + esc(h) + '</h3>'; }).join('');
    var paras = (p.paragraphs || []).map(function (t) { return '<p>' + esc(t) + '</p>'; }).join('');
    var imgs = (p.images || []).map(function (s) { return '<img loading="lazy" src="' + esc(s) + '" alt="">'; }).join('');
    var links = (p.links || []).map(function (l) {
      return '<a class="link" href="' + esc(l) + '" target="_blank" rel="noopener">' + esc(l) + '</a>';
    }).join('');
    document.getElementById('content').innerHTML =
      '<h1>' + esc(p.title || p.path) + '</h1>' +
      '<div class="crumb">' + esc(p.path) + (p.lang ? ' &middot; ' + esc(p.lang) : '') + '</div>' +
      (p.description ? '<p class="desc">' + esc(p.description) + '</p>' : '') +
      heads + paras +
      (imgs ? '<div class="imgs">' + imgs + '</div>' : '') +
      (links ? '<h3>Links</h3><div class="links">' + links + '</div>' : '');
  }
  function render() {
    var p = route();
    if (p === '/') renderHome();
    else if (BY_PATH[p]) renderPage(BY_PATH[p]);
    else document.getElementById('content').innerHTML = '<p>Not found: ' + esc(p) + '</p>';
    renderNav();
  }
  fetch('data/pages.json')
    .then(function (r) { return r.json(); })
    .then(function (data) {
      PAGES = data.pages || [];
      BY_PATH = {};
      PAGES.forEach(function (p) { BY_PATH[p.path] = p; });
      if (data.root) document.getElementById('origin').textContent = 'clone of ' + data.root;
      render();
    })
    .catch(function (e) {
      document.getElementById('content').innerHTML = '<p>Failed to load dataset: ' + esc(e.message) + '</p>';
    });
  window.addEventListener('hashchange', render);
})();
`;

const SHELL_CSS = `
* { box-sizing: border-box; }
body { margin: 0; color: #222; background: #fff; font-size: 16px; line-height: 1.6; }
.topbar { display: flex; align-items: center; gap: 1rem; padding: 0.9rem 1.5rem; background: #111; color: #fff; }
.brand { color: #fff; text-decoration: none; font-weight: 700; font-size: 1.15rem; }
.origin { color: #999; font-size: 0.85rem; margin-left: auto; text-align: right; }
.layout { display: flex; min-height: calc(100vh - 110px); }
.sidebar { width: 280px; flex: 0 0 280px; padding: 1rem 0.5rem; border-right: 1px solid #e8e8e8; overflow: auto; max-height: calc(100vh - 110px); position: sticky; top: 54px; }
.content { flex: 1; padding: 2rem; max-width: 960px; }
.footer { padding: 1rem 1.5rem; border-top: 1px solid #e8e8e8; color: #888; font-size: 0.85rem; }
.nav-group { padding: 0.75rem 1rem 0.35rem; font-size: 0.72rem; letter-spacing: 0.08em; text-transform: uppercase; color: #999; }
.nav-item { display: block; padding: 0.35rem 1rem; color: #333; text-decoration: none; font-size: 0.9rem; border-radius: 4px; }
.nav-item:hover { background: #f2f2f2; }
.nav-item.active { background: #111; color: #fff; }
.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 1rem; }
.card { display: block; border: 1px solid #e8e8e8; border-radius: 8px; padding: 1rem; color: inherit; text-decoration: none; }
.card:hover { border-color: #111; }
.card-title { font-weight: 700; }
.card-path { color: #999; font-size: 0.8rem; margin: 0.25rem 0; }
.card-desc { color: #555; font-size: 0.85rem; }
.crumb { color: #999; font-size: 0.85rem; margin-bottom: 1rem; }
.desc { color: #444; }
.imgs { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1rem; margin: 1rem 0; }
.imgs img { width: 100%; height: auto; border-radius: 6px; }
.links { display: flex; flex-direction: column; gap: 0.25rem; }
.link { color: #06c; word-break: break-all; }
.loading { color: #999; }
`;

function tokenStylesheet(tokens: Record<string, string>): string {
  const vars = Object.entries(tokens)
    .filter(([, v]) => v && v.trim().length > 0)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return vars.length > 0 ? `:root {\n${vars}\n}\n` : '';
}

function typographyStylesheet(fonts: string[]): string {
  const stack = [...fonts, 'sans-serif']
    .filter((f) => f && f.trim().length > 0)
    .map((f) => (/^['"]/.test(f) ? f : `"${f}"`))
    .join(', ');
  return stack.length > 0 ? `body { font-family: ${stack}; }\n` : '';
}

export function generateSite(dataset: SiteDataset, capture?: CaptureBundle): GeneratedSite {
  const css = tokenStylesheet(capture?.cssTokens ?? {}) + typographyStylesheet(capture?.fonts ?? []) + SHELL_CSS;

  const files: GeneratedSiteFile[] = [
    { path: 'index.html', content: INDEX_HTML },
    { path: 'app.js', content: APP_JS },
    { path: 'style.css', content: css },
    { path: 'data/pages.json', content: JSON.stringify(dataset, null, 2) },
    { path: 'vercel.json', content: '{\n  "cleanUrls": true\n}\n' },
  ];

  return { index: 'index.html', files };
}
